# Generated by Django 6.0.4 on 2026-05-26 01:50

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import netbox_cisco_aci.validators
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('netbox_cisco_aci', '0005_switch_interface_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACIContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('scope', models.CharField(default='context', max_length=32)),
                ('qos_class', models.CharField(blank=True, max_length=16)),
                ('target_dscp', models.CharField(blank=True, max_length=32)),
                ('aci_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='netbox_cisco_aci.acitenant')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Contract',
                'verbose_name_plural': 'ACI Contracts',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIContractRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('role', models.CharField(max_length=16)),
                ('aci_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='netbox_cisco_aci.acicontract')),
                ('aci_endpoint_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_relations', to='netbox_cisco_aci.aciendpointgroup')),
                ('aci_endpoint_security_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_relations', to='netbox_cisco_aci.aciendpointsecuritygroup')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Contract Relation',
                'verbose_name_plural': 'ACI Contract Relations',
                'ordering': ('aci_contract', 'role'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('aci_tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filters', to='netbox_cisco_aci.acitenant')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Filter',
                'verbose_name_plural': 'ACI Filters',
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIFilterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('ether_type', models.CharField(default='unspecified', max_length=16)),
                ('ip_protocol', models.CharField(blank=True, default='unspecified', max_length=16)),
                ('source_port_from', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('source_port_to', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('destination_port_from', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('destination_port_to', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)])),
                ('tcp_rules', models.CharField(blank=True, max_length=64)),
                ('match_only_fragments', models.BooleanField(default=False)),
                ('arp_opcode', models.CharField(blank=True, max_length=8)),
                ('stateful', models.BooleanField(default=False)),
                ('icmp_v4_type', models.CharField(blank=True, max_length=16)),
                ('icmp_v6_type', models.CharField(blank=True, max_length=16)),
                ('aci_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='netbox_cisco_aci.acifilter')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Filter Entry',
                'verbose_name_plural': 'ACI Filter Entries',
                'ordering': ('aci_filter', 'name'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACISubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('apply_both_directions', models.BooleanField(default=True)),
                ('reverse_filter_ports', models.BooleanField(default=True)),
                ('qos_class', models.CharField(blank=True, max_length=16)),
                ('target_dscp', models.CharField(blank=True, max_length=32)),
                ('aci_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='netbox_cisco_aci.acicontract')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Subject',
                'verbose_name_plural': 'ACI Subjects',
                'ordering': ('aci_contract', 'name'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACISubjectFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('direction', models.CharField(default='both', max_length=8)),
                ('action', models.CharField(default='permit', max_length=16)),
                ('priority', models.CharField(default='default', max_length=16)),
                ('aci_filter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_attachments', to='netbox_cisco_aci.acifilter')),
                ('aci_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_attachments', to='netbox_cisco_aci.acisubject')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Subject Filter',
                'verbose_name_plural': 'ACI Subject Filters',
                'ordering': ('aci_subject', 'aci_filter', 'direction'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='acisubject',
            name='filters',
            field=models.ManyToManyField(blank=True, related_name='subjects', through='netbox_cisco_aci.ACISubjectFilter', to='netbox_cisco_aci.acifilter'),
        ),
        migrations.AddConstraint(
            model_name='acicontract',
            constraint=models.UniqueConstraint(fields=('aci_tenant', 'name'), name='netbox_cisco_aci_acicontract_tenant_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='acicontractrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('aci_endpoint_group__isnull', False)), fields=('aci_contract', 'aci_endpoint_group', 'role'), name='netbox_cisco_aci_acicontractrelation_epg_unique'),
        ),
        migrations.AddConstraint(
            model_name='acicontractrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('aci_endpoint_security_group__isnull', False)), fields=('aci_contract', 'aci_endpoint_security_group', 'role'), name='netbox_cisco_aci_acicontractrelation_esg_unique'),
        ),
        migrations.AddConstraint(
            model_name='acifilter',
            constraint=models.UniqueConstraint(fields=('aci_tenant', 'name'), name='netbox_cisco_aci_acifilter_tenant_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='acifilterentry',
            constraint=models.UniqueConstraint(fields=('aci_filter', 'name'), name='netbox_cisco_aci_acifilterentry_filter_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='acisubjectfilter',
            constraint=models.UniqueConstraint(fields=('aci_subject', 'aci_filter', 'direction'), name='netbox_cisco_aci_acisubjectfilter_unique'),
        ),
        migrations.AddConstraint(
            model_name='acisubject',
            constraint=models.UniqueConstraint(fields=('aci_contract', 'name'), name='netbox_cisco_aci_acisubject_contract_name_unique'),
        ),
    ]
