# Generated by Django 6.0.4 on 2026-05-26 03:06

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import netbox_cisco_aci.validators
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0001_initial'),
        ('extras', '0001_initial'),
        ('netbox_cisco_aci', '0006_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACIInterfaceFabricMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('interface_role', models.CharField(default='host', max_length=16)),
                ('aci_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface_memberships', to='netbox_cisco_aci.acinode')),
                ('dcim_interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aci_fabric_membership', to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Interface Fabric Membership',
                'verbose_name_plural': 'ACI Interface Fabric Memberships',
                'ordering': ('aci_node', 'dcim_interface'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIStaticPortBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('binding_type', models.CharField(default='regular', max_length=32)),
                ('encap_vlan', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('mode', models.CharField(default='regular', max_length=16)),
                ('primary_encap_vlan', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4094)])),
                ('deployment_immediacy', models.CharField(default='lazy', max_length=16)),
                ('aci_endpoint_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='static_port_bindings', to='netbox_cisco_aci.aciendpointgroup')),
                ('dcim_interface', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aci_static_port_bindings', to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Static Port Binding',
                'verbose_name_plural': 'ACI Static Port Bindings',
                'ordering': ('aci_endpoint_group', 'dcim_interface', 'encap_vlan'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIVPCBindingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('binding_a', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpc_pair_as_a', to='netbox_cisco_aci.acistaticportbinding')),
                ('binding_b', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpc_pair_as_b', to='netbox_cisco_aci.acistaticportbinding')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI vPC Binding Pair',
                'verbose_name_plural': 'ACI vPC Binding Pairs',
                'ordering': ('binding_a',),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIDomainBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('deployment_immediacy', models.CharField(default='lazy', max_length=16)),
                ('resolution_immediacy', models.CharField(default='lazy', max_length=16)),
                ('aci_domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='epg_bindings', to='netbox_cisco_aci.acidomain')),
                ('aci_endpoint_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='domain_bindings', to='netbox_cisco_aci.aciendpointgroup')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI Domain Binding',
                'verbose_name_plural': 'ACI Domain Bindings',
                'ordering': ('aci_endpoint_group', 'aci_domain'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('aci_endpoint_group', 'aci_domain'), name='netbox_cisco_aci_acidomainbinding_unique')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='acistaticportbinding',
            constraint=models.UniqueConstraint(fields=('aci_endpoint_group', 'dcim_interface', 'encap_vlan'), name='netbox_cisco_aci_acistaticportbinding_unique'),
        ),
        migrations.AddConstraint(
            model_name='acivpcbindingpair',
            constraint=models.UniqueConstraint(fields=('binding_a',), name='netbox_cisco_aci_acivpcbindingpair_a_unique'),
        ),
        migrations.AddConstraint(
            model_name='acivpcbindingpair',
            constraint=models.CheckConstraint(condition=models.Q(('binding_a', models.F('binding_b')), _negated=True), name='netbox_cisco_aci_acivpcbindingpair_distinct'),
        ),
    ]
