# Generated by Django 6.0.4 on 2026-05-26 13:52

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import netbox_cisco_aci.validators
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('netbox_cisco_aci', '0008_l3outs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACIL3OutStaticRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('prefix', models.CharField(max_length=43)),
                ('track_policy', models.CharField(blank=True, max_length=64)),
                ('preference', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)])),
                ('route_controls', models.JSONField(blank=True, default=list)),
                ('aci_logical_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_routes', to='netbox_cisco_aci.acilogicalnode')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI L3Out Static Route',
                'verbose_name_plural': 'ACI L3Out Static Routes',
                'ordering': ('aci_logical_node', 'prefix'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ACIL3OutStaticRouteNextHop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=64, validators=[netbox_cisco_aci.validators.aci_policy_name_validator])),
                ('name_alias', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('nexthop_address', models.CharField(blank=True, max_length=43)),
                ('nexthop_type', models.CharField(default='prefix', max_length=16)),
                ('preference', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('aci_static_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_hops', to='netbox_cisco_aci.acil3outstaticroute')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'ACI L3Out Static Route Next Hop',
                'verbose_name_plural': 'ACI L3Out Static Route Next Hops',
                'ordering': ('aci_static_route', 'nexthop_address'),
                'abstract': False,
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='acil3outstaticroute',
            constraint=models.UniqueConstraint(fields=('aci_logical_node', 'prefix'), name='netbox_cisco_aci_acil3outstaticroute_node_prefix_unique'),
        ),
        migrations.AddConstraint(
            model_name='acil3outstaticroutenexthop',
            constraint=models.UniqueConstraint(fields=('aci_static_route', 'nexthop_address'), name='netbox_cisco_aci_acil3outstaticroutenexthop_route_addr_unique'),
        ),
    ]
